window.Platformer = window.Platformer || {};

// Auto-generated by scripts/write_build_info.py during packaging.
Platformer.BUILD_VERSION = "2026.02.15.1151";
Platformer.BUILD_TIME_UTC = "2026-02-15T11:51:11.006323Z";
Platformer.BUILD_UPDATE_REPO = "zyynx-hub/Platformer";
Platformer.BUILD_UPDATE_CHANNEL = "stable";
Platformer.BUILD_UPDATE_ENABLED = true;
