window.Platformer = window.Platformer || {};

// Auto-generated by scripts/write_build_info.py during packaging.
Platformer.BUILD_VERSION = "2026.02.16.1512";
Platformer.BUILD_TIME_UTC = "2026-02-16T15:12:21.461317Z";
Platformer.BUILD_UPDATE_REPO = "";
Platformer.BUILD_UPDATE_CHANNEL = "stable";
Platformer.BUILD_UPDATE_ENABLED = true;
Platformer.BUILD_DEBUG = false;
