from datetime import datetime, timezone
from pathlib import Path
import os


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = root / "js" / "core" / "build-info.js"
    now = datetime.now(timezone.utc)
    version = now.strftime("%Y.%m.%d.%H%M")
    ts = now.isoformat().replace("+00:00", "Z")
    update_repo = os.getenv("UPDATE_GH_REPO", "").strip().strip("/")
    update_channel = os.getenv("UPDATE_CHANNEL", "stable").strip() or "stable"
    update_enabled_raw = os.getenv("UPDATE_ENABLED", "true").strip().lower()
    update_enabled = "false" not in update_enabled_raw and update_enabled_raw not in ("0", "off", "no")

    content = (
        "window.Platformer = window.Platformer || {};\n\n"
        "// Auto-generated by scripts/write_build_info.py during packaging.\n"
        f'Platformer.BUILD_VERSION = "{version}";\n'
        f'Platformer.BUILD_TIME_UTC = "{ts}";\n'
        f'Platformer.BUILD_UPDATE_REPO = "{update_repo}";\n'
        f'Platformer.BUILD_UPDATE_CHANNEL = "{update_channel}";\n'
        f"Platformer.BUILD_UPDATE_ENABLED = {str(update_enabled).lower()};\n"
    )
    out_path.write_text(content, encoding="utf-8")
    print(f"[build-info] version={version} time={ts}")
    print(f"[build-info] update_repo={update_repo or '(none)'} channel={update_channel} enabled={update_enabled}")
    print(f"[build-info] wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
